# Generated by Django 5.0.5 on 2024-07-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
